services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=80
    network_mode: service:torrentvpn
    volumes:
      - "{{ docker_dir }}/sabnzbd/config:/config"
      - "/bigboi/media:/media"
    restart: unless-stopped

  torrentvpn:
    image: "lscr.io/linuxserver/wireguard"
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: torrentvpn
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "{{ docker_dir }}/sabnzbd/wg0.conf:/config/wg0.conf"
    restart: unless-stopped
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.{{ dns_name }}`)"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"
      - "traefik.http.routers.sabnzbd.entrypoints=https"
      - "traefik.http.routers.sabnzbd.tls.certresolver=godaddy"

networks:
  proxy:
    external: true
