services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=80
    volumes:
      - "{{ docker_dir }}/media/sabnzbd/config:/config"
      - "/bigboi/media:/media"
    restart: unless-stopped
    networks:
      media:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.{{ dns_name }}`)"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"
      - "traefik.http.routers.sabnzbd.entrypoints=https"
      - "traefik.http.routers.sabnzbd.tls.certresolver=godaddy"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - "{{ docker_dir }}/media/prowlarr/config:/config"
      - "/bigboi/media:/media"
    restart: unless-stopped
    networks:
      media:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.{{ dns_name }}`)"
      - "traefik.http.routers.prowlarr.entrypoints=https"
      - "traefik.http.routers.prowlarr.tls.certresolver=godaddy"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - "{{ docker_dir }}/media/radarr/config:/config"
      - "/bigboi/media:/media"
    restart: unless-stopped
    networks:
      media:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.{{ dns_name }}`)"
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.tls.certresolver=godaddy"
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - "{{ docker_dir }}/media/sonarr/config:/config"
      - "/bigboi/media:/media"
    restart: unless-stopped
    networks:
      media:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.{{ dns_name }}`)"
      - "traefik.http.routers.sonarr.entrypoints=https"
      - "traefik.http.routers.sonarr.tls.certresolver=godaddy"

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - "{{ docker_dir }}/media/lidarr/config:/config"
      - "/bigboi/media:/media"
    restart: unless-stopped
    networks:
      media:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.{{ dns_name }}`)"
      - "traefik.http.routers.lidarr.entrypoints=https"
      - "traefik.http.routers.lidarr.tls.certresolver=godaddy"

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "{{ uid }}"
    volumes:
      - "{{ docker_dir }}/media/jellyfin/config:/config"
      - "{{ docker_dir }}/media/jellyfin/cache:/cache"
      - "{{ docker_dir }}/media/jellyfin/transcodes:/transcodes"
      - "/bigboi/media:/media"
    restart: unless-stopped
    runtime: nvidia
    networks:
      media:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.{{ dns_name }}`)"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.tls.certresolver=godaddy"

networks:
  media:
  proxy:
    external: true
